### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by skyfallsss** [cambridgeltl/visual-med-alpaca#3]
I couldn't download the ROCO dataset via running the scripts.

**Comment by wdayang** [comment]
I cannot either, shows error

**Comment by skyfallsss** [comment]
Exception: Giving up download of archive ftp://ftp.ncbi.nlm.nih.gov/pub/pmc/oa_package/e5/85/PMC5638292.tar.gz after 11 tries

**Comment by wdayang** [comment]
same error

**Comment by anchen1011** [comment]
We've double checked and the script should work. It's likely a network issue.
